cargo-features = ["strip", "named-profiles"]

[package]
name = "rustcraft"
version = "0.2.0"
authors = ["Marshall Ashdowne <daarkzek@protonmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
overflow-checks = false
strip = "symbols"
lto = true
debug = 0
panic = 'abort'
codegen-units = 1

[build]
target = "wasm32-unknown-unknown"

[target.'cfg(target_arch = "wasm32")'.release]
opt-level = 's'

[dependencies]
rc_network = { path = "./rc_network" }
rc_logging = { path = "./logging" }
wgpu = "0.8.1"
gfx-hal = "0.5.3"
nalgebra = "0.21.0"
noise = "0.6.0"
image = "0.23.3"
zerocopy = "0.2.8"
lazy_static = "1.4.0"
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.61", default-features = false, features = ["std", "preserve_order"] }
env_logger = "0.7"
bytemuck = "1.2.0"
futures = { version = "0.3", features = ["compat"] }
byteorder = "1.3.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
specs = {version = "0.16.1"} #specs = {version = "0.16.1", default-features = false}
winit = { version = "0.22.2"}
instant = { version = "0.1" }
systemstat = "0.1.5"
zip = {version = "0.5.5", default-features = false}
rand = { version = "0.7.3" }
sysinfo = "0.16.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
instant = { version = "0.1", features = [ "now", "wasm-bindgen" ] }
winit = { version = "0.22.2", features = ["web-sys"]}
zip = {version = "0.5.5", default-features = false, features = ["deflate"]}
wasm-bindgen = "0.2.73"
js-sys = "0.3.39"
wasm-bindgen-futures = "0.4.12"
specs = { version = "0.16.1", default-features = false, features = ["wasm-bindgen"] }