[package]
name = "rustcraft"
version = "0.1.0"
authors = ["Marshall Ashdowne <daarkzek@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[profile.release]
debug = true
overflow-checks = true

[dependencies]
wgpu = "0.4.0"
winit = "0.21.0"
cgmath = "0.17.0"
noise = "0.6.0"
rand = "0.7.3"
image = "0.23.3"
shaderc = "0.6.2"
zerocopy = "0.2.8"
systemstat = "0.1.5"
zip = "0.5.5"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.7"
collision = "0.20.1"