[package]
name = "rustcraft"
version = "0.1.0"
authors = ["Marshall Ashdowne <daarkzek@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[profile.release]
debug = true
overflow-checks = true

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "32de700ef908029cc5f8ac3b0befd7439f5bd7bd" }
gfx-hal = "0.5.3"
nalgebra = "0.21.0"
noise = "0.6.0"
image = "0.23.3"
zerocopy = "0.2.8"
lazy_static = "1.4.0"
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
log = "0.4"
env_logger = "0.7"
bytemuck = "1.2.0"
futures = { version = "0.3", features = ["compat"] }
specs = "0.16.1"
byteorder = "1.3.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = { version = "0.22.2"}
instant = { version = "0.1" }
systemstat = "0.1.5"
zip = {version = "0.5.5"}
rand = { version = "0.7.3" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
instant = { version = "0.1", features = [ "now", "wasm-bindgen" ] }
winit = { version = "0.22.2", features = ["web-sys"]}
zip = {version = "0.5.5", default-features = false, features = ["deflate"]}
wasm-bindgen = "0.2.62"
web-sys = { version = "0.3.39", features = [ "Document", "Navigator", "Node", "NodeList", "Gpu", "GpuAdapter", "GpuAddressMode", "GpuBindGroup", "GpuBindGroupEntry", "GpuBindGroupDescriptor", "GpuBindGroupLayout", "GpuBindGroupLayoutEntry", "GpuBindGroupLayoutDescriptor", "GpuBlendDescriptor", "GpuBlendFactor", "GpuBlendOperation", "GpuBindingType", "GpuBuffer", "GpuBufferBinding", "GpuBufferCopyView", "GpuBufferDescriptor", "GpuCanvasContext", "GpuColorDict", "GpuColorStateDescriptor", "GpuCommandBuffer", "GpuCommandBufferDescriptor", "GpuCommandEncoder", "GpuCommandEncoderDescriptor", "GpuCompareFunction", "GpuComputePassDescriptor", "GpuComputePassEncoder", "GpuComputePipeline", "GpuComputePipelineDescriptor", "GpuCullMode", "GpuDepthStencilStateDescriptor", "GpuDevice", "GpuDeviceDescriptor", "GpuExtent3dDict", "GpuFilterMode", "GpuFrontFace", "GpuIndexFormat", "GpuInputStepMode", "GpuLimits", "GpuLoadOp", "GpuOrigin3dDict", "GpuPipelineLayout", "GpuPipelineLayoutDescriptor", "GpuPowerPreference", "GpuPrimitiveTopology", "GpuProgrammableStageDescriptor", "GpuQueue", "GpuRasterizationStateDescriptor", "GpuRenderPassColorAttachmentDescriptor", "GpuRenderPassDepthStencilAttachmentDescriptor", "GpuRenderPassDescriptor", "GpuRenderPassEncoder", "GpuRenderPipeline", "GpuRenderPipelineDescriptor", "GpuRequestAdapterOptions", "GpuSampler", "GpuSamplerDescriptor", "GpuShaderModule", "GpuShaderModuleDescriptor", "GpuStencilOperation", "GpuStencilStateFaceDescriptor", "GpuStoreOp", "GpuSwapChain", "GpuSwapChainDescriptor", "GpuTexture", "GpuTextureAspect", "GpuTextureComponentType", "GpuTextureCopyView", "GpuTextureDescriptor", "GpuTextureDimension", "GpuTextureFormat", "GpuTextureViewDescriptor", "GpuTextureViewDimension", "GpuTextureView", "GpuVertexAttributeDescriptor", "GpuVertexBufferLayoutDescriptor", "GpuVertexFormat", "GpuVertexStateDescriptor", "GpuVertexAttributeDescriptor", "HtmlCanvasElement", "Window",]}
js-sys = "0.3.39"
wasm-bindgen-futures = "0.4.12"