[package]
name = "AshLearning"
version = "0.1.0"
authors = ["Marshall Ashdowne <daarkzek@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.4.0"
winit = "0.21.0"
cgmath = "0.17.0"
noise = "0.6.0"
rand = "0.7.3"
image = "0.23.1"
glsl-to-spirv = "0.1"
zerocopy = "0.2.8"
specs = "0.16.1"
wgpu_glyph = "0.7.0"
systemstat = "0.1.5"