[package]
name = "rustcraft-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
byteorder = "*"
serde = "1.0.145"
thiserror = "1.0.37"